services:
  spark-master:
    image: apache/spark:4.1.0-preview3-python3
    container_name: spark-master
    environment:
      - PYTHONPATH=/opt/spark/python:/opt/spark/python/lib/py4j-0.10.9.9-src.zip
    command: >
      /opt/spark/bin/spark-class
      org.apache.spark.deploy.master.Master
      --host spark-master
      --port 7077
      --webui-port 8080
    ports:
      - "7077:7077"
      - "8080:8080"
      - "4040:4040"
    volumes:
      - ./:/opt/spark/work-dir:rw

  spark-worker:
    image: apache/spark:4.1.0-preview3-python3
    container_name: spark-worker
    depends_on:
      - spark-master
    command: >
      /opt/spark/bin/spark-class
      org.apache.spark.deploy.worker.Worker
      spark://spark-master:7077
    ports:
      - "8081:8081"
    volumes:
      - ./:/opt/spark/work-dir:rw
